version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: annekgomes
      POSTGRES_PASSWORD: root1
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U annekgomes -d database"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: