version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@fpf10
      POSTGRES_DB: postegress
    ports:
      - "5433:5433"
