version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: SeuBanco
      POSTGRES_PASSWORD: SuaSenha
      POSTGRES_DB: SeuBanco
    ports:
      - "5433:5433"
